version: '3.8'

services:
  # Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservices_net

  # Services
  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: inventory-service
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ms_express
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    networks:
      - microservices_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@host.docker.internal:3306/ms_fastapi
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
    networks:
      - microservices_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  microservices_net:
    driver: bridge
